version: '3'
services:
  app:
    build: .
    ports:
      - "8082:8082"
    networks:
      - spring
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring
networks:
  spring:
    external: true