name: Java Prod CD with Gradle

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml

      - name: Create application-dev.yml
        run: |
          touch ./src/main/resources/application-dev.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> ./src/main/resources/application-dev.yml

      - name: Create application-prod-cd.yml
        run: |
          touch ./src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" >> ./src/main/resources/application-prod.yml

      - name: Create application-test.yml
        run: |
          mkdir ./src/test/resources
          touch ./src/test/resources/application.yml
          echo "${{ secrets.APPLICATION_TEST_YML }}" >> ./src/test/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEDEPLOY_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CODEDEPLOY_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://dotori-jar/jar/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name dotori-app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name prod --s3-location bucket=dotori-jar,bundleType=zip,key=jar/$GITHUB_SHA.zip

      - name: Dotori Prod Server CD Success Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: 🎉 Dotori Prod Server CD 🐿
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Dotori Prod Server CD Fail Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❌ Dotori Prod Server CD 🐿
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000